require:
  - "rubocop-md"

Markdown:
  # Whether to run RuboCop against non-valid snippets
  WarnInvalid: true
  # Whether to lint codeblocks without code attributes
  Autodetect: true

AllCops:
  NewCops: enable
